### ISSUE TITLE
err running server.py: 'Linear4bitLt' object has no attribute 'g_idx'

### ISSUE THREAD

**Issue by urbien** [s4rduk4r/alpaca_lora_4bit_readme#6]
thank you for your tutorial. This is a third tutorial I am trying to get through. Failed with 2 others due to mismatches between Python, Torch, CUDA, and other versions.
But on the last line it fails when I submit a prompt from the WebUI. I appreciate any help.

Traceback (most recent call last):
  File "/home/tadle-325a/alpaca_lora_4bit/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/tadle-325a/alpaca_lora_4bit/text-generation-webui/modules/text_generation.py", line 220, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/peft/tuners/lora.py", line 686, in forward
    result = super().forward(x)
  File "/home/tadle-325a/alpaca_lora_4bit/text-generation-webui/autograd_4bit.py", line 134, in forward
    self.g_idx, self.bits, self.maxq,
  File "/home/tadle-325a/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear4bitLt' object has no attribute 'g_idx'
Output generated in 0.37 seconds (0.00 tokens/s, 0 tokens, context 59)

**Comment by s4rduk4r** [comment]
Judging by the last lines it has something to do with how the model is being opened. Probably you'll need to switch into triton background somehow. I'm not using this UI so can't give you specifics, unfortunately. I saw a new UI in docker - maybe it'll be easier to start. Alternatively you could use `inference.py`, but there need to be done some adjustments probably

**Comment by s4rduk4r** [comment]
@urbien
I've looked into the issue and updated [instructions](https://github.com/s4rduk4r/alpaca_lora_4bit_readme/blob/main/README.md#6-use-model-for-inference) on how to load GPTQv2 models. Please try them and tell if everything works or doesn't work
